<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>DispatchEventsExport</AssemblyName></PropertyGroup><ItemGroup><Reference Include="Microsoft.Diagnostics.Tracing.TraceEvent"><HintPath>../../tracer/Microsoft.Diagnostics.Tracing.TraceEvent.dll</HintPath></Reference><Reference Include="Microsoft.Diagnostics.FastSerialization"><HintPath>../../tracer/Microsoft.Diagnostics.FastSerialization.dll</HintPath></Reference><Reference Include="Microsoft.Diagnostics.NETCore.Client"><HintPath>../../tracer/Microsoft.Diagnostics.NETCore.Client.dll</HintPath></Reference></ItemGroup></Project>
