exclude:
- /examples/.*
- /src/VSIntegration/.*
- /src/Docs/.*
- /src/NLogAutoLoadExtension/.*
- /src/InstallNLogConfig/.*
- /tests/SampleExtensions/.*
- /tools/.*
component_depth: 3
languages:
- csharp
