<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <Deterministic>true</Deterministic><Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Lokad.Onnx"><HintPath>../../product/Lokad.Onnx.dll</HintPath></Reference>
    <Reference Include="Google.Protobuf"><HintPath>../../product/Google.Protobuf.dll</HintPath></Reference>
  </ItemGroup>
</Project>
