<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>FingerprintDeployment</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Lokad.Onnx"><HintPath>$(FrozenProductDirectory)/Lokad.Onnx.dll</HintPath></Reference>
    <Reference Include="Google.Protobuf"><HintPath>$(FrozenProductDirectory)/Google.Protobuf.dll</HintPath></Reference>
    <Reference Include="Microsoft.ML.OnnxRuntime"><HintPath>$(FrozenOrtDirectory)/Microsoft.ML.OnnxRuntime.dll</HintPath></Reference>
  </ItemGroup>
</Project>
